---
abstract: 'The POD-like markup language written for podcats.in'
author:
  - 'Altreus <altreus@perl.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Cats
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1.11
  Data::Dumper: 0
  List::Util: 1.21
  Parser::MGC: 0.06
  Test::More: 0
version: 0.04
