--- #YAML:1.0
name:               Pod-Cats
version:            0.02
abstract:           The POD-like markup language written for podcats.in
author:
    - Altreus <altreus@perl.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          1.11
    Data::Dumper:  0
    List::Util:    1.21
    Parser::MGC:   0.06
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
